# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region  = "ap-southeast-1"

}

provider "aws" {
  region  = "us-east-1"
  alias   = "certificates"
}

terraform {
#   backend "s3" {
#     bucket = "trustonic-tfstates-alps-ut"
#     key    = "terraform-states/ut/ttp3/terraform.tfstate"
#     region = "eu-west-1"
#     dynamodb_table = "trustonic-terraform-alps-ut-state-lock-dynamo"
#   }
}